apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
  namespace: budget
data:
  appsettings.Production.json: |
    {
      "ConnectionStrings": {
        "budgetdb": "{{dbConnectionString}}",
        "nats": "{{natsConnectionString}}"
      },
      "Authentication": {
        "Authority": "{{authAuthority}}",
        "Audiences": ["{{authIssuer}}"],
        "Issuer": "{{authIssuer}}",
        "AllowedOrigins": ["https://budget.timo-hermans.nl", "https://budget2.timo-hermans.nl"]
      },
    }
