apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: budget
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: secret-store
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'backend-vault'
      containers:
        - name: backend
          image: registry.timo-hermans.nl/budget-api:2025.8.2
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config-map
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secret-store
              mountPath: /mnt/secrets-store
              readOnly: true
      imagePullSecrets:
        - name: regcred
