apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: budget
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`budget-api.timo-hermans.nl`)
      services:
        - name: backend-budget
          port: 80
  tls:
    certResolver: default
    domains:
      - main: budget-api.timo-hermans.nl