apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrations
  namespace: budget
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600  
  template:
    spec:
      volumes:
        - name: secret-store
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'backend-vault'
        - name: appsettings-template
          configMap:
            name: backend-config-map
        - name: appsettings-final
          emptyDir: {}
      initContainers:
        - name: appsettings-prep
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /template/appsettings.json /app/appsettings.json
              sed -i "s/{{dbConnectionString}}/$(cat /mnt/secrets-store/dbConnectionString)/" /app/appsettings.json
          volumeMounts:
            - name: secret-store
              mountPath: /mnt/secrets-store
              readonly: true
            - name: appsettings-template
              mountPath: /template
              readOnly: true
            - name: appsettings-final
              mountPath: /app
      containers:
      - name: ef-migrations
        image: registry.timo-hermans.nl/budget-migrations-runner:2025.9.11.3
        volumeMounts:
        - name: appsettings-final
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
