apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrations
  namespace: budget
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600  
  template:
    spec:
      volumes:
        - name: secret-store
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'backend-vault'
      containers:
      - name: ef-migrations
        image: registry.timo-hermans.nl/budget-api-migrations:20250808.1
        command: ["dotnet", "ef", "database", "update"]
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: backend-db-migrations-configmap
        volumeMounts:
        - name: secret-store
          mountPath: /mnt/secrets-store
          readOnly: true
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
