repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgres
    namespace: auth
    chart: bitnami/postgresql
    version: 16.7.4
    values:
      - ./helm/postgres/values.yaml