apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      volumes:
        - name: nats-config
          secret:
            secretName: nats
      containers:
        - name: nats
          image: nats:2.11.9-alpine
          args: ["-c", "/etc/nats-config/nats.conf"]
          ports:
            - containerPort: 4222
          volumeMounts:
            - name: nats-config
              mountPath: /etc/nats-config
              subPath: nats.conf
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi