apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nats-vault
  namespace: budget
spec:
  provider: vault
  parameters:
    roleName: 'zolder'
    objects: |
      - objectName: "USERNAME"
        secretPath: "zolder/data/budget"
        secretKey: "natsUsername"
      - objectName: "PASSWORD"
        secretPath: "zolder/data/budget"
        secretKey: "natsPassword"
