apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: budget
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: secret-store
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'frontend-vault'
      containers:
        - name: frontend
          image: registry.timo-hermans.nl/budget-app:2025.8.15
          envFrom:
            - secretRef:
                name: frontend-secret
            - configMapRef:
                name: frontend-configmap
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secret-store
              mountPath: /mnt/secrets-store
              readOnly: true
      imagePullSecrets:
        - name: regcred
