apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: budget
  namespace: budget
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`budget.timo-hermans.nl`)
      services:
        - name: frontend
          port: 80
  tls:
    certResolver: default
    domains:
      - main: budget.timo-hermans.nl