---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-auth
  namespace: registry
spec:
  encryptedData:
    htpasswd: AgATGT3B6IQSPLeGbKr30pN1ux4cZEVk2FrF+DxAX15SGcYotAhoORwmqoxIt/WwwWxSBfYjdekYC79574XusLXXsHWuOXZBLl9Oov99j9ToO8b0ekFFF+e5hJYZR82X18h0YGifWnyN/KBgmDgsVSV36SkX1+Z/4WBWczjsSOWE9svKr0rkFvsBGOBTZ37f9UJjECZrPrJgS5QBq5tARg9lShkdaS85KRAzJxv1o4uDH500B7CTVPnhO13IR2BXrrkavNowM6xFiUYvfnAlVIDR762oVk9JOXdfS0BlHqj3oE6IG4pqRYOYHS0mX10dmCquFaDaru4ScVsRfWNGZRD8lbVlDFmRK/ji/ZuRShoZw7V15Ig0c5SMvOA7ldNipq+AEz8Ht2TYqgNWxtoA9QaIrQnvvnAoT0Tz5DDLee3OShBvtlWYlLYAY0tf3fvSmsDrxuF6UlusMqTIVaCHdWzC8hJz7EPcZTC1cXTTO/aJ6LMLJEsTxZhiWSGuHE7AAQkrMM7Jxjr/5L14pbSP7SPKOZTc7+ne4XsIFVXJkklfeyZonThVJ9bzbBYEXx341A4TZBvIeN/078iJlQHRIhQnesmorqdYOfATCSNqZXiw+dv/EWSR5cnet73H+hWJ91/6AH+xDlWK0+qa7ESNAcpJAsciWFaXTWrOnedKRo0jrjiEIugiNxW9sqHh6j/7Gbg9ajwehYiYO1+2VXt5wbb96RxU/Tr0K4MV/a8erSli6a+9JMbUL9GQMXxTMHm9kPLi/NJj2sdrCMotqbmh3dUmJNo=
  template:
    metadata:
      creationTimestamp: null
      name: registry-auth
      namespace: registry
    type: Opaque
