apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: registry-registry-transport@kubernetescrd
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000