---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: auth
spec:
  encryptedData:
    password: AgBGNLO5u0iwfgIS18PZp3etpuj7vxnVaw/1GJCTcbHzrzwF7FB/6wpIGxDgFyxqLpB1VqSrMwfgLQn5hCt0lt55jzLUAGW/f3VC4BC2TsrwEVwkfIyYMeWSLpAwJrKJYeQo3aGu1GX36deafY61mW7i5e2pDQ2S6cNYB/4A/TgP5NGbv2gXQZosuT/EzEEvAAvOIc16uA900BcPGO/1RJvhHZEOh/7Thd6gCWO4xTOv4+1IzJbDlVWROSxdozH995ZClS37zlCG+aoBH0gcga52Wern4YHr2b7l6vdJ5yxH+FhqDNxmBbRHPTf6ZV2ruTBw20Zeq3oVWJV1Ky4f60dAzrfdAOAKC9trZMvdE/Ob5h3hPGTYNSrIoAN3XFcobcZ0CPv4h8F2+ycCFDJh8RZu6jfT5xXx1qX5ndETw7yL8xU7Fxqr33FXauwalt/z776HpFoeF+GvTzxvzUN7Fgls9OV0iH0ICJ4RPJELLU2sY7cCLnv3g7+PMJrL3W3s/gTYMwvEHQRLNuIBdZvpCttcKuj12gcr07r/fBqe36I/xUJqp/OEuHph72+FGVNhzVrf4l55caHYpiwGWIerbpQNFW3s/7aypiPpVsMhOr9jtMQowI7aYpFoDi3Vwu09aUyQbubbtvlrAZ/4gQHUHM+mfx7TdgY1tspjrV76BvT0z/q+PVujwJCzq18odaA6fH8L5+SyMyRnAYtYQNCLUf9h+CBRaWaxSmQSrBWGQCvi8ExR9tbdB7R3YlRncrxvFZ6GKQ85xfk4gzAdZMLNcw==
    postgres-password: AgA6EpV22yGHrJkx3lvREuCA1obeYDlWMLf4U6/1YmvjrNGm4yKi3daIyELf2sXF3+NOAD1+5DIsOdkUKMl35yfYaGygHo/mItmIYcm2JBhWhwObnhvLeLOCVIBXiZb/iGp+HE2yqkSlZGsGprO5ahiflZnverzjgxEjuDbNdnHVeg+bfQPkK+eExD9g6EHg491hroug6ylYzGtsAIjorzqLYT1uWxzao8ly9XPwO76Yd004Q6wR6ZUu+nHe1FVoNovN6VRlNZAfQEazUGogqBdWKaca05s9zE7YheTzqYmzuNW1Z+2vtlwQNNu0R/0j59eqNCMiwrrlNI9VlV2Y/CpUh0QACMs4Jt3WI/MJTyxm28q0nILdVzvD+g8PjfsUMIlanMlDDb6D/835aTRn1iM/YdHzISpX0HK4DNMTZz9NYvp/XiK6zO0tgZh5FwNcD4h2uZj+W7YhDLEW/OLuk/xxcPHQGe2Z5DOheVOAIpykkuS2xGnR1BXDGYmvnay0Tl0s9W8Tu1kKl3s+QX+fhoC1FLiA9XLvTtzgsKCzlnXzqA8y8UNQ2qUK/JF8Tfk3WF8LA9X7gUgebFrQ8GC8/Av39+eNprjH6CyhRyn3Qb3W3gt3k309yTwEy6EqSk5OJoHy85JmDBudJUuPThJ6/AXbHU6FvT43GJ8neaPXOQBEw8z0gReRvAlAhLDssR/DflNc8iQcIyILbjhP3Wq03ApJ5uiY7qHV9fVXyg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: auth
    type: Opaque
