apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq-budget
  namespace: budget
spec:
  selector:
    matchLabels:
      app: mq-budget
  serviceName: mq-budget
  replicas: 1
  template:
    metadata:
      labels:
        app: mq-budget
    spec:
      initContainers:
        - name: merge-config
          image: alpine
          command:
            - sh
            - -c
            - |
              echo "default_user = $(cat /etc/secrets/default_user)" > /etc/rabbitmq/rabbitmq.conf
              echo "default_password = $(cat /etc/secrets/default_password)" >> /etc/rabbitmq/rabbitmq.conf
              echo "generated rabbitmq.conf"
              chmod 644 /etc/rabbitmq/rabbitmq.conf
          volumeMounts:
            - name: secrets-store
              mountPath: /etc/secrets
              readOnly: true
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          ports:
            - containerPort: 5672
          volumeMounts:
            - name: secrets-store
              mountPath: /etc/rabbitmq
              readOnly: true
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: secrets-store
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'mq-vault'