apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/budget
    repoURL: 'https://github.com/timohermans/cluster.git'
    targetRevision: HEAD
  destination:
    namespace: budget
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true