apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/external-secrets
    repoURL: 'https://github.com/timohermans/cluster.git'
    targetRevision: HEAD
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true