apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-db
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.7.9
    helm:
      releaseName: postgresql
      valueFiles:
        - ../k8s/keycloak/values-db.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: auth