apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-db
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.7.9
    helm:
      releaseName: postgresql
      valuesObject:
        global:
          postgresql:
            auth:
              username: sleutelmantel
              database: keycloak
              existingSecret: postgres-secret
  destination:
    server: "https://kubernetes.default.svc"
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true