apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-app
spec:
  project: default
  source:
    path: k8s/registry
    repoURL: 'https://github.com/timohermans/cluster.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'