apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  source:
    chart: k8s/sealed-secrets
    repoURL: https://github.com/timohermans/cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default