apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  source:
    path: k8s/sealed-secrets
    targetRevision: HEAD
    repoURL: 'https://github.com/timohermans/cluster.git'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default