apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    helm:
      releaseName: vault
      valuesObject:
        ui:
          enabled: true
        server: 
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: vault.timo-hermans.nl
                paths:
                  - /
            tls:
              - hosts:
                  - vault.timo-hermans.nl
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls.certresolver: default
        injector:
          enabled: false
        csi:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true