apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: auth
spec:
  selector:
    matchLabels:
      app: auth-db
  serviceName: auth-db
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: keycloak-db-vault
            - configMapRef:
                name: auth-db-config-map
          volumes:
            - name: secret-store
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: keycloak-vault
          volumeMounts:
            - name: auth-db-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: auth-db-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
