server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: auth.timo-hermans.nl
        paths:
          - /
    tls:
      - hosts:
          - vault.timo-hermans.nl
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: default